spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: stephnews
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: ${DATABASE_URL}
      database: ${DATABASE_NAME}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: An application to view news and informations
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

gcp:
  config:
    file: stephnews-f7426be12afe.json
  project:
    id: stephnews
  bucket:
    id: stephnews
  dir:
    name: dev

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}

logging:
  level:
    web: info